NAME : Ganesh

SUBJECTS :
  - Maths
  - Science
  - Physics

EDUCATION:
  TENTH_SCHOOL : Bhashyam Public School
  INTERMEDIATE : Narayana Junior College
  B_TECH : JNIT College
  MASTERS : Northwestern Polytechnical university
  TEST :
    - hjbcw
    - wbcjbw
    - wbcjbwn

  # TEST1 : *name
  
  TEST2 :
    jwcbwjbc : nwjcbw
    jabcjabc : bajcbaj
    cvsjc : ncjkbw