apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pods
  template:
    metadata:
      labels:
        app: pods
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
