apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    app: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-deploy-ctr
        image: polinux/stress
        resources:
          requests:
            memory: "300Mi"
          limits:
            memory: "350Mi"
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
