name: "test"

on:
   workflow_dispatch:

jobs:
  job1:
    test:
      runs-on: ubuntu-latest


      steps:
        - name: hello
          run: echo "hello world"

  job2:
    test1:
      needs: job1
      runs-on: ubuntu-latest

        steps:
          - name: hola
            run: echo "hello ganesh!"