name: "test"

on:
   workflow_dispatch:
     inputs:
       user_name:
         description: "Enter Username"
         type: string
         required: true


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo to runner
        uses: actions/checkout@v2

      - name: hello
        id: gani
        run: echo "name= ${{ github.event.inputs.user_name }}" >> $GITHUB_OUTPUT
    outputs:
      name: ${{ steps.gani.outputs.name  }}

  test1:
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
      - name: hola
        run: echo ${{ needs.test.outputs.name }}