name: "test"

on:
   workflow_dispatch:
     inputs:
       user_name:
         description: "Enter Username"
         type: string
         required: true


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo to runner
        uses: actions/checkout@v2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Run Terraform 
        uses: sarathkrish/invoke-terraform-run-api@v1.0
        continue-on-error: true
        
      - name: hello
        id: gani
        run: echo "name= ${{ github.event.inputs.user_name }}" >> $GITHUB_OUTPUT

      - name: hola
        run: echo ${{ steps.gani.outputs.name }}
