name: "test"

on:
   workflow_dispatch:
     inputs:
       user_name:
         description: "Enter Username"
         type: string
         required: true


jobs:
  test:
    runs-on: ubuntu-latest

      steps:
        - name: checkout repo to runner
          uses: actions/checkout@v2

        - name: hello
          id: gani
          run: echo "hello world ${{ inputs.user_name }}" >> $GITHUB_OUTPUT
      outputs:
        name: ${{ steps.gani.outputs.name }}

  test1:
    needs: ["test"]
      runs-on: ubuntu-latest

      steps:
        - name: hola
          run: echo "hello ganesh! ${{ needs.test.outputs.name }}"