name: "test"

on:
   workflow_dispatch:
     inputs:
       user_name:
         description: "Enter Username"
         type: string
         required: true


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo to runner
        uses: actions/checkout@v2

      - name: hello
        id: gani
        run: echo "hello world ${{ inputs.user_name }}" >> $GITHUB_OUTPUT

      - name: hola
        run: echo "hello ganesh! ${{ steps.gani.outputs.name }}"